apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nexus-python-test-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.cluster-sgjnd.sgjnd.sandbox371.opentlc.com/repository/tssc-qe-test/smatula/nexus-python-test-3:4725d1d1cf03f27031c34f27fb33fdf77fc81267@sha256:f0394a5ec423d096b1c86a520cbba652f64d4230428531d396e9595a9d625fe4
          name: container-image
