apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nexus-python-test-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nexus-python-test-3 
  name: nexus-python-test-3
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nexus-python-test-3 
